#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#spring:
#  application:
#    name: order
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL57Dialect
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: w123456
#    url: jdbc:mysql://localhost:3306/we_sell?characterEncoding=utf-8&serverTimezone=UTC
#user:
#  name: wuu
#  age: 12